version: '3.8'
services:
  web:
    build: 
      context: .
      target: runner
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped